/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', "Aptos", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        display: ['"Newsreader"', '"STIX Two Text"', "Georgia", "serif"],
        serif: ['"Newsreader"', '"STIX Two Text"', "Georgia", "serif"],
        math: ['"STIX Two Text"', '"STIX Two Math"', "Georgia", "serif"],
        mono: ['"IBM Plex Mono"', '"SF Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "edge-label": ["var(--type-edge-label)", { lineHeight: "1.1" }],
        "ui-tiny": ["var(--type-ui-tiny)", { lineHeight: "1.15" }],
        "ui-2xs": ["var(--type-ui-2xs)", { lineHeight: "1.15" }],
        "ui-caption": ["var(--type-ui-caption)", { lineHeight: "1.25" }],
        "ui-hint": ["var(--type-ui-hint)", { lineHeight: "1.35" }],
        "ui-meta": ["var(--type-ui-meta)", { lineHeight: "1.35" }],
        "ui-xs": ["var(--type-ui-xs)", { lineHeight: "1.4" }],
        "ui-control": ["var(--type-ui-control)", { lineHeight: "1.25" }],
        "ui-sm": ["var(--type-ui-sm)", { lineHeight: "1.5" }],
        "ui-copy": ["var(--type-ui-copy)", { lineHeight: "1.6" }],
        "ui-body": ["var(--type-ui-body)", { lineHeight: "1.5" }],
        "ui-lead": ["var(--type-ui-lead)", { lineHeight: "1.5" }],
        "atlas-brand": ["var(--type-atlas-brand)", { lineHeight: "1" }],
        "atlas-card": ["var(--type-atlas-card)", { lineHeight: "1.15" }],
        "node-panel-title": ["var(--type-node-panel-title)", { lineHeight: "1.08" }],
        "atlas-panel": ["var(--type-atlas-panel)", { lineHeight: "1.06" }],
        "atlas-summary": ["var(--type-atlas-summary)", { lineHeight: "1.25" }],
        "atlas-display": ["var(--type-atlas-display)", { lineHeight: "1.1" }],
      },
      letterSpacing: {
        label: "var(--tracking-label)",
        "label-wide": "var(--tracking-label-wide)",
        "label-tight": "var(--tracking-label-tight)",
      },
      colors: {
        bg: "var(--bg)",
        "bg-deep": "var(--bg-deep)",
        surface: {
          DEFAULT: "var(--surface)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
        },
        fg: {
          1: "var(--fg-1)",
          2: "var(--fg-2)",
          3: "var(--fg-3)",
          4: "var(--fg-4)",
        },
        border: "var(--border)",
        hairline: "var(--hairline)",
        accent: {
          DEFAULT: "var(--accent)",
          soft: "var(--accent-soft)",
          border: "var(--accent-border)",
        },
        domain: {
          blue: "var(--blue)",
          green: "var(--green)",
          purple: "var(--purple)",
          red: "var(--red)",
          teal: "var(--teal)",
          orange: "var(--orange)",
          pink: "var(--pink)",
          gold: "var(--gold)",
        },
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        card: "var(--shadow-1)",
        cardHover: "var(--shadow-2)",
        float: "var(--shadow-3)",
        panel: "-4px 0 24px rgba(15,23,42,0.06)",
      },
      borderRadius: {
        pill: "999px",
      },
    },
  },
  plugins: [],
};
